<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%
    // 🛡️ STRICT RBAC ENFORCEMENT
    String role = (String) session.getAttribute("userRole");
    if (!"ADMIN".equals(role)) {
        response.sendRedirect(request.getContextPath() + "/login.jsp");
        return;
    }
%>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Administrator Guide | OceanView Admin</title>
    <link rel="stylesheet" href="<%= request.getContextPath() %>/css/admin_ui.css">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&family=Playfair+Display:wght@700&display=swap" rel="stylesheet">
</head>
<body>

<!-- ══════════════════════════════════════════════
     SIDEBAR
══════════════════════════════════════════════ -->
<aside class="admin-sidebar">
    <div class="sidebar-brand">
        <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>
        <span>OceanView Admin</span>
    </div>
    <div class="sidebar-role">Administrator</div>
    <nav class="sidebar-nav">
        <a href="dashboard.jsp"    class="nav-link">        <span class="nav-icon">📊</span> Dashboard</a>
        <a href="manage_users.jsp" class="nav-link">        <span class="nav-icon">👥</span> Staff Access</a>
        <a href="admin_ledger.jsp" class="nav-link">        <span class="nav-icon">📋</span> Billing Ledger</a>
        <a href="help.jsp"         class="nav-link active"><span class="nav-icon">📖</span> Guide</a>
        <div class="sidebar-divider"></div>
    </nav>
    <div class="sidebar-footer">
        <a href="<%= request.getContextPath() %>/logout" class="btn-logout">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline points="16 17 21 12 16 7"/><line x1="21" y1="12" x2="9" y2="12"/></svg>
            Secure Logout
        </a>
    </div>
</aside>

<!-- ══════════════════════════════════════════════
     MAIN CONTENT
══════════════════════════════════════════════ -->
<main class="admin-main">

    <!-- Executive Header -->
    <div class="exec-header">
        <div>
            <h1>System Administration Guide</h1>
            <p>A master guide to overseeing the OceanView Enterprise Operations.</p>
        </div>
        <div class="status-badge">
            <div class="status-dot"></div>
            <span>Help & Documentation</span>
        </div>
    </div>

    <!-- Help Grid -->
    <div class="grid grid-2">

        <!-- Topic 1: BI -->
        <div class="card">
            <div class="card-header">
                <div>
                    <div class="card-title" style="display: flex; align-items: center; gap: 12px;">
                        <span style="font-size: 1.5rem;">📊</span>
                        Business Intelligence (BI)
                    </div>
                </div>
            </div>
            <div style="padding: 20px;">
                <p>The Executive Dashboard provides real-time financial transparency. The <strong>Gross Revenue Yield</strong> is calculated instantly based on every invoice generated by your staff. No manual calculation is required.</p>
                <div style="background: #fffbeb; border: 1px solid #fcd34d; color: #92400e; padding: 15px; border-radius: 8px; font-size: 0.9rem; margin-top: 15px;">
                    💡 <strong>Tip:</strong> The "System Status" indicator in the top right automatically checks database connectivity every time you load the page.
                </div>
            </div>
        </div>

        <!-- Topic 2: Audit Trail -->
        <div class="card">
            <div class="card-header">
                <div>
                    <div class="card-title" style="display: flex; align-items: center; gap: 12px;">
                        <span style="font-size: 1.5rem;">🛡️</span>
                        Security & Audit Trail
                    </div>
                </div>
            </div>
            <div style="padding: 20px;">
                <p>The black "Live Audit Console" on your dashboard connects directly to the database security layer. It records high-priority events (like new bookings or cancellations) automatically.</p>
                <p>This ensures that if a staff member makes a mistake, you have a timestamped record of exactly when it happened.</p>
            </div>
        </div>

        <!-- Topic 3: User Management -->
        <div class="card">
            <div class="card-header">
                <div>
                    <div class="card-title" style="display: flex; align-items: center; gap: 12px;">
                        <span style="font-size: 1.5rem;">👥</span>
                        Managing Staff Access
                    </div>
                </div>
            </div>
            <div style="padding: 20px;">
                <p>Use the <strong>Staff Access</strong> tab to view all authorised personnel. The system uses <strong>Role-Based Access Control (RBAC)</strong>.</p>
                <p><strong>ADMIN:</strong> Full access to financials and logs.<br><strong>STAFF:</strong> Restricted to bookings and invoicing only.</p>
                <p style="margin-top:12px;">Use the <strong>+ Add Account</strong> button to create new staff or admin accounts directly from the browser — passwords are automatically hashed with SHA-256 + salt.</p>
            </div>
        </div>

        <!-- Topic 4: Billing Ledger -->
        <div class="card">
            <div class="card-header">
                <div>
                    <div class="card-title" style="display: flex; align-items: center; gap: 12px;">
                        <span style="font-size: 1.5rem;">📋</span>
                        Billing Ledger
                    </div>
                </div>
            </div>
            <div style="padding: 20px;">
                <p>The <strong>Billing Ledger</strong> gives you full visibility into every reservation and invoice — with a live daily revenue trend chart and per-room revenue breakdown. Unlike the staff view, you see the entire billing history.</p>
                <p>Print past invoices for guest disputes directly from the Ledger action menu.</p>
            </div>
        </div>

    </div>

    <!-- Footer -->
    <div style="margin-top: 50px; text-align: center; color: var(--admin-muted); font-size: 0.9rem;">
        <p>OceanView Resort Management System v3.0 (Enterprise Edition)</p>
        <p>Need technical support? Contact the IT Department.</p>
    </div>

</main>
</body>
</html>
