package oceanview.dao;

import oceanview.util.DatabaseFactory;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Enterprise Business Intelligence Data Access Object.
 * Responsible for aggregating financial and operational metrics.
 */
public class ReportDAO {

    /**
     * Calculates Total Gross Revenue securely using BigDecimal.
     */
    public BigDecimal getTotalRevenue() {
        String sql = "SELECT SUM(grand_total_lkr) as total FROM ov_billing_invoice";
        try (Connection conn = DatabaseFactory.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            if (rs.next() && rs.getBigDecimal("total") != null) {
                return rs.getBigDecimal("total");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return BigDecimal.ZERO;
    }

    /**
     * Calculates the total number of active/past bookings.
     */
    public int getTotalBookingsCount() {
        String sql = "SELECT COUNT(reservation_pk) as count FROM ov_reservation";
        try (Connection conn = DatabaseFactory.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            if (rs.next()) return rs.getInt("count");
        } catch (Exception e) { e.printStackTrace(); }
        return 0;
    }

    /**
     * Aggregates booking volume per room category for occupancy insights.
     */
    public Map<String, Integer> getCategoryPerformance() {
        Map<String, Integer> stats = new LinkedHashMap<>();
        String sql = "SELECT c.category_name, COUNT(r.reservation_pk) as count " +
                     "FROM ov_room_category c " +
                     "LEFT JOIN ov_accommodation a ON c.category_id = a.category_id " +
                     "LEFT JOIN ov_reservation r ON a.room_pk = r.room_pk " +
                     "GROUP BY c.category_name ORDER BY count DESC";

        try (Connection conn = DatabaseFactory.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                stats.put(rs.getString("category_name"), rs.getInt("count"));
            }
        } catch (Exception e) { e.printStackTrace(); }
        return stats;
    }

    /**
     * Retrieves the latest system audit logs generated by MySQL Triggers.
     */
    public List<String> getRecentAuditLogs(int limit) {
        List<String> logs = new ArrayList<>();
        String sql = "SELECT action_type, description, log_time " +
                     "FROM ov_audit_log ORDER BY log_time DESC LIMIT ?";

        try (Connection conn = DatabaseFactory.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, limit);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    String time = rs.getTimestamp("log_time").toString().substring(0, 16);
                    logs.add("[" + time + "] " + rs.getString("action_type") + " - " + rs.getString("description"));
                }
            }
        } catch (Exception e) { e.printStackTrace(); }
        return logs;
    }
}
